version: '3.4'

services:
  eventbus:
    container_name: OrderWalletEventBusRabbitMQ
    image: rabbitmq:3-management-alpine
    restart: always
    #environment:
    #- RABBITMQ_DEFAULT_USER=myuser
    #- RABBITMQ_DEFAULT_PASS=mypassword
    ports:
    # AMQP protocol port
    - '5672:5672'
    # HTTP management UI
    - '15672:15672'

  basketservice.api:
    image: ${DOCKER_REGISTRY-}basketserviceapi
    build:
      context: .
      dockerfile: BasketService/BasketService.API/Dockerfile
    ports:
        - "4000:80"
    depends_on:
        - basketservice-redis-server

  basketservice-redis-server:
    container_name: BasketServiceRedisServer
    image: redis:7-bullseye
    restart: always
    ports:
        - "6379:6379"
    volumes:
        - basketservicecache:/data

  orderservice.api:
    image: ${DOCKER_REGISTRY-}orderserviceapi
    build:
      context: .
      dockerfile: OrderService/OrderService.API/Dockerfile
    ports:
        - "4001:80"
    depends_on:
        - orderservice-postgres-server
        - orderservice-redis-server
   
  orderservice-postgres-server:
    container_name: OrderServicePostgresServer
    image: postgres:14-bullseye
    ports:
        - "5432:5432"
    environment:
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: postgres
    volumes:
        - orderservicedatabase:/var/lib/postgresql/data

  walletservice-postgres-server:
    container_name: WalletServicePostgresServer
    image: postgres:14-bullseye
    ports:
        - "5433:5432"
    environment:
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: postgres
    volumes:
        - walletservicedatabase:/var/lib/postgresql/data

  orderservice-redis-server:
    container_name: OrderServiceRedisServer
    image: redis:7-bullseye
    restart: always
    ports:
        - "6380:6379"
    volumes:
        - orderservicecache:/data

  walletservice.api:
    image: ${DOCKER_REGISTRY-}walletserviceapi
    build:
      context: .
      dockerfile: WalletService/WalletService.API/Dockerfile
    ports:
        - "4002:80"


volumes:
  orderservicedatabase:
  orderservicecache:
    driver: local
  basketservicecache:
    driver: local
  walletservicedatabase:
    